openapi: 3.0.0
info:
  title: Services API
  version: 1.0.0
  description: API for managing services and related resources
  contact:
    name: Brian Sappey
    email: brian.sappey@example.com

servers:
  - url: /api/v1
    description: API v1 server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

  schemas:
    Error:
      type: object
      properties:
        error:
          type: boolean
          example: true
        messages:
          type: array
          items:
            type: string
          example: ["Error message 1", "Error message 2"]
        statusCode:
          type: integer
          example: 422
        statusText:
          type: string
          example: "Unprocessable Entity"

    BudgetEstimatorRequest:
      type: object
      required:
        - account_id
        - campaign_id
        - start_date
        - end_date
        - daily_budget
        - target_audience
        - bidding_strategy
      properties:
        account_id:
          type: integer
          description: The ID of the account
          example: 123
        campaign_id:
          type: integer
          description: The ID of the campaign
          example: 456
        start_date:
          type: string
          format: date
          description: The start date of the campaign
          example: "2024-03-20"
        end_date:
          type: string
          format: date
          description: The end date of the campaign
          example: "2024-04-20"
        daily_budget:
          type: number
          format: float
          description: The daily budget amount
          example: 100.00
        target_audience:
          type: object
          required:
            - age_min
            - age_max
            - gender
            - location
            - interests
          properties:
            age_min:
              type: integer
              description: Minimum age of target audience
              example: 18
            age_max:
              type: integer
              description: Maximum age of target audience
              example: 65
            gender:
              type: array
              items:
                type: string
              description: Target gender(s)
              example: ["male", "female"]
            location:
              type: array
              items:
                type: string
              description: Target location(s)
              example: ["US", "CA"]
            interests:
              type: array
              items:
                type: string
              description: Target interest(s)
              example: ["sports", "technology"]
        bidding_strategy:
          type: string
          description: The bidding strategy to use
          example: "maximize_conversions"

    BudgetEstimatorResponse:
      type: object
      properties:
        account_id:
          type: integer
          description: The ID of the account
          example: 123
        campaign_id:
          type: integer
          description: The ID of the campaign
          example: 456
        start_date:
          type: string
          format: date
          description: The start date of the campaign
          example: "2024-03-20"
        end_date:
          type: string
          format: date
          description: The end date of the campaign
          example: "2024-04-20"
        daily_budget:
          type: number
          format: float
          description: The daily budget amount
          example: 100.00
        total_budget:
          type: number
          format: float
          description: The total budget for the campaign period
          example: 3200.00
        days:
          type: integer
          description: Number of days in the campaign
          example: 32
        target_audience:
          $ref: '#/components/schemas/BudgetEstimatorRequest/properties/target_audience'
        bidding_strategy:
          type: string
          description: The bidding strategy used
          example: "maximize_conversions"
        estimated_audience_size:
          type: integer
          description: Estimated size of the target audience
          example: 1000000
        estimated_impressions:
          type: integer
          description: Estimated number of impressions
          example: 5000000
        estimated_clicks:
          type: integer
          description: Estimated number of clicks
          example: 50000
        estimated_conversions:
          type: integer
          description: Estimated number of conversions
          example: 5000

paths:
  /budget-estimator:
    post:
      summary: Estimate campaign budget
      description: Estimates the budget and audience metrics for a campaign based on provided parameters
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BudgetEstimatorRequest'
      responses:
        '200':
          description: Budget estimation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BudgetEstimatorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error' 
